monitoring:
  port: 16300

status:
  port: 16301

storages:
  - name: main
    plugin: fs
    config:
      directory: /var/lib/yandex/unified_agent/main
      max_partition_size: 1gb
      max_segment_size: 500mb

channels:
  - name: cloud_monitoring
    channel:
      pipe:
        - storage_ref:
            name: main
      output:
        plugin: yc_metrics
        config:
          folder_id: b1gchsq9rppdno9li997
          iam:
            cloud_meta: {}
routes:
  - input:
      plugin: metrics_pull
      config:
        url: http://localhost:8404/metrics
        format:
          prometheus: {}
    channel:
      channel_ref:
        name: cloud_monitoring
