---
- name: Finish scripts
  hosts: all
  become: true
  tasks:
    - name: Execute prepare_db command
      command:
        cmd: bingo prepare_db
      become_user: ubuntu
    - name: Create index for sessions
      ansible.builtin.command:
        cmd: psql -h 10.0.0.6 -U postgres -c 'create index on sessions(id);'
    - name: Create index for customers
      ansible.builtin.command:
        cmd: psql -h 10.0.0.6 -U postgres -c 'create index on customers(id);'