student_email: arsinux@yandex.com
postgres_cluster:
  hosts:
  - address: 10.0.0.6
    port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  ssl_mode: disable
  use_closest_node: false